name: Build CI

on:
  push:
  pull_request:
jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Publish
        run: |
          dotnet publish EDRoutePlanner -c release -p:PublishSingleFile=true -p:PublishTrimmed=true --framework=net5.0 --runtime win-x64 -o build
          if ($? -eq $false) { Exit 1 }

      - name: Delete .pdb
        run: rm build/EDRoutePlanner.pdb

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EDRoutePlanner
          path: build
